node_exporter:
  - node_cpu_seconds_total
  - node_memory_MemAvailable_bytes
  - node_memory_MemFree_bytes

process_exporter:
  - namedprocess_namegroup_cpu_seconds_total
  - namedprocess_namegroup_memory_bytes