---
# edge server configuration parameters
# cache parameters
cache.expiration: 60
cache.cleanup: 60
cache.size: 10

# server api parameters
api.port: 1323
etcd.address: "localhost:2379"

# container management
containers.pool.memory: 1000
container.expiration: 30
janitor.interval: 30

# offloading parameters
cloud.server.url: "http://127.0.0.1:1324"
offloading: true