---
# edge server configuration parameters
# cache parameters
cache.expiration: 3600 # Seconds <----
cache.cleanup: 300 # Seconds <-----
cache.size: 20 #items in cache

# server api parameters
api.port: 1323
etcd.address: "localhost:2379"

# container management
container.pool.memory: 2048 #MB
container.expiration: 600 # Seconds <----
janitor.interval: 600 # Seconds <------


# execution report logger management
logging.cleanInterval: 10 # minutes
logging.expiration: 5 # minutes

#registration
registry.nearby.interval: 40 #Seconds
registry.monitoring.interval: 90 # Seconds
registry.ttl: 90 #Seconds

#drop management
policy.drop.expiration: 30 # Seconds

# offloading parameters
cloud-server-url: "http://127.0.0.1:1324"

offloading: true
scheduler.policy: "qosaware"
cloud: false
registry.udp.port: 9876