Idle:
  node-exporter: pause
  process-exporter: pause
  otel-collector: pause
  prometheus: pause
Disabled:
  node-exporter: stop
  process-exporter: stop
  otel-collector: stop
  prometheus: stop
PartialPerformance:
  node-exporter: run
  process-exporter: pause
  otel-collector: pause
  prometheus: run
FullPerformance:
  node-exporter: run
  process-exporter: run
  otel-collector: run
  prometheus: run
