Idle:
  node-exporter: run
  process-exporter: pause
  cadvisor: pause
  prometheus: pause
Disabled:
  node-exporter: run
  process-exporter: stop
  cadvisor: stop
  prometheus: stop
PartialPerformance:
  node-exporter: run
  process-exporter: run
  cadvisor: pause
  prometheus: run
FullPerformance:
  node-exporter: run
  process-exporter: run
  cadvisor: run
  prometheus: run
