Degraded:
  node:
    cpu: 25.0
    ram: 35.0
  monitoring_system:
    cpu: 10.0
    ram: 10.0
Critical:
  node:
    cpu: 35.0
    ram: 45.0
  monitoring_system:
    cpu: 15.0
    ram: 15.0
Inactive:
  node:
    cpu: 60.0
    ram: 80.0
  monitoring_system:
    cpu: 25.0
    ram: 25.0